name: SandboxAQ AQtive Guard AI SPM Inventory Scan
description: Scans the repository contents for AI usage and reports findings back to AQtive Guard by SandboxAQ.
author: SB Technology Inc.
branding:
  icon: alert-triangle
  color: yellow
inputs: 
  aqg_instance:
    description: URL of your AQtive Guard instance
    required: false
    default: ''
  aqg_client_id:
    description: Client ID for authentication
    required: false
    default: ''
  aqg_client_secret:
    description: Client secret for authentication
    required: false
    default: ''
runs:
  using: composite
  steps:
      - name: Run Free Scan
        if: ${{ inputs.aqg_instance == '' || inputs.aqg_client_id == '' || inputs.aqg_client_secret == '' }}
        shell: bash
        run: |
          echo "Job triggered by ${{ github.event_name }}, running on ${{ github.repository }} @ ${{ github.ref }}"
          curl -X GET --output image.tar "https://artifactregistry.googleapis.com/download/v1/projects/pqc-ml-vertexai/locations/europe-west1/repositories/aispm-public-generic/files/aispm-scanner-github:1.0.0:aispm_inventory_scanner-1.0.0.tar.gz:download?alt=media"
          # Load image into the local docker cache
          docker load --input image.tar
          # Tag the image, so it doesn't try and pull it from the web (and then we reference the tag subsequently)
          docker tag bazel/saq/pqc/aispm_inventory:latest aispm-action-test:latest
          # The usual way would be doing this via "uses: docker://image:tag" but that doesn't work with local images
          # since GH Actions tries to pull them from the web. So we run it manually here.
          docker run --rm -e "HOME" -e GITHUB_WORKSPACE="/github/workspace" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_ACTOR -e GITHUB_EVENT_NAME -e GITHUB_REPOSITORY -e GITHUB_REF -e GITHUB_SHA -e GITHUB_STEP_SUMMARY_PATH="summary.md" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v $GITHUB_WORKSPACE:"/github/workspace" aispm-action-test:latest --summary-output ${{ github.workspace }}/summary.json
          if [ -f "summary.md" ]; then
            cat summary.md >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run Paid Scan
        if: ${{ inputs.aqg_instance != '' && inputs.aqg_client_id != '' && inputs.aqg_client_secret != '' }}
        shell: bash
        env: 
          AQG_INSTANCE: ${{ inputs.aqg_instance }}
          AQG_CLIENT_ID: ${{ inputs.aqg_client_id }}
          AQG_CLIENT_SECRET: ${{ inputs.aqg_client_secret }}
        run: |
          echo "Job triggered by ${{ github.event_name }}, running on ${{ github.repository }} @ ${{ github.ref }}"
          # Use client ID and secret to obtain an AQG token from the instance.
          # Store the token received in the AQG_TOKEN environment variable.          
          echo AQG_TOKEN=$(curl -s -L -X POST $AQG_INSTANCE/authv2/realms/aqtiveguard/protocol/openid-connect/token -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=client_credentials" -d "client_id=$AQG_CLIENT_ID" -d "client_secret=$AQG_CLIENT_SECRET" | jq -r ".access_token") >> "$GITHUB_ENV"
          # Get the image as a tar. Authenticate using AQG_TOKEN.
          curl -s -L --output image.tar $AQG_INSTANCE/downloads/sensors/aispm_inventory_scanner/1.0.0 -H "Authorization: Bearer $AQG_TOKEN"
          # Load image into the local docker cache
          docker load --input image.tar
          # Tag the image, so it doesn't try and pull it from the web (and then we reference the tag subsequently)
          docker tag bazel/saq/pqc/aispm_inventory:latest aispm-action-test:latest
          # The usual way would be doing this via "uses: docker://image:tag" but that doesn't work with local images
          # since GH Actions tries to pull them from the web. So we run it manually here.
          docker run --rm -e "HOME" -e GITHUB_WORKSPACE="/github/workspace" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_ACTOR -e GITHUB_EVENT_NAME -e GITHUB_REPOSITORY -e GITHUB_REF -e GITHUB_SHA -e AQG_TOKEN -e AQG_INSTANCE="$AQG_INSTANCE" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v $GITHUB_WORKSPACE:"/github/workspace" aispm-action-test:latest
